import type { Event } from "@/entities/event/model";

export const mockEvents: Event[] = [
  {
    id: "evt_rock-night",
    title: "Neon Brush",
    description: "Pinte no escuro em uma noite imersiva com musica, luzes e experiencias ao vivo.",
    imageUrl:
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    startsAt: "2026-11-02T21:00:00.000-03:00",
    venueName: "Novotel Music City",
    address: "Av. Principal, 1000",
    city: "Sao Paulo",
    price: 120,
    currency: "BRL",
    capacity: 120,
    availableTickets: 84,
    seatingMode: "seat-map",
    status: "published",
    externalSource: "ticketmaster",
    externalId: "tm_rock-night",
  },
  {
    id: "evt_indie-session",
    title: "Glass House",
    description: "Festival visual com artistas independentes, instalacoes e apresentacoes curtas.",
    imageUrl:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    startsAt: "2026-12-12T19:30:00.000-03:00",
    venueName: "Teatro Luz",
    address: "Rua das Flores, 48",
    city: "Sao Paulo",
    price: 86,
    currency: "BRL",
    capacity: 80,
    availableTickets: 32,
    seatingMode: "seat-map",
    status: "published",
    externalSource: "manual",
  },
  {
    id: "evt-ballet-dawn",
    title: "Dawn Ballet",
    description: "Espetaculo de ballet contemporaneo com sessao unica e assentos numerados.",
    imageUrl:
      "https://images.unsplash.com/photo-1508807526345-15e9b5f4eaff?auto=format&fit=crop&w=1200&q=80",
    startsAt: "2026-12-20T20:00:00.000-03:00",
    venueName: "Theatro Municipal",
    address: "Praca Ramos de Azevedo",
    city: "Sao Paulo",
    price: 98,
    currency: "BRL",
    capacity: 140,
    availableTickets: 41,
    seatingMode: "seat-map",
    status: "published",
    externalSource: "ticketmaster",
    externalId: "tm_ballet-dawn",
  },
];
