import type { Event } from "@/entities/event/model";

export const mockEvents: Event[] = [
  {
    id: "evt_rock-night",
    title: "Neon Brush",
    description: "Pinte no escuro em uma noite imersiva com musica, luzes e experiencias ao vivo.",
    about:
      "Neon Brush e uma experiencia criativa para quem quer sair da rotina e viver uma noite diferente. O encontro mistura pintura guiada, luz negra, musica ambiente e uma atmosfera de festa intimista para voce criar sua propria obra enquanto aproveita o evento. Nao precisa ter experiencia previa: a proposta e relaxar, experimentar cores, conhecer pessoas e levar para casa uma lembranca visual da noite.",
    imageUrl:
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    startsAt: "2026-11-02T21:00:00.000-03:00",
    venueName: "Novotel Music City",
    address: "Av. Principal, 1000",
    city: "Sao Paulo",
    price: 120,
    currency: "BRL",
    capacity: 120,
    availableTickets: 84,
    seatingMode: "seat-map",
    status: "published",
    externalSource: "ticketmaster",
    externalId: "tm_rock-night",
  },
  {
    id: "evt_indie-session",
    title: "Glass House",
    description: "Festival visual com artistas independentes, instalacoes e apresentacoes curtas.",
    about:
      "Glass House reune artistas independentes, instalacoes visuais e apresentacoes curtas em um formato facil de explorar. A programacao foi pensada para circular sem pressa entre ambientes, descobrir novos criadores e acompanhar pequenas performances ao longo da noite. E uma boa escolha para quem gosta de arte contemporanea, musica e encontros culturais em espacos mais proximos do publico.",
    imageUrl:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    startsAt: "2026-12-12T19:30:00.000-03:00",
    venueName: "Teatro Luz",
    address: "Rua das Flores, 48",
    city: "Sao Paulo",
    price: 86,
    currency: "BRL",
    capacity: 80,
    availableTickets: 32,
    seatingMode: "seat-map",
    status: "published",
    externalSource: "manual",
  },
  {
    id: "evt-ballet-dawn",
    title: "Dawn Ballet",
    description: "Espetaculo de ballet contemporaneo com sessao unica e assentos numerados.",
    about:
      "Dawn Ballet apresenta uma leitura contemporanea do ballet classico, combinando movimento, luz e trilha sonora em uma sessao unica. A experiencia foi desenhada para valorizar a proximidade com o palco e a escolha do assento, por isso os ingressos sao numerados. E um evento indicado para quem busca uma noite elegante, visualmente marcante e com ritmo mais contemplativo.",
    imageUrl:
      "https://images.unsplash.com/photo-1508807526345-15e9b5f4eaff?auto=format&fit=crop&w=1200&q=80",
    startsAt: "2026-12-20T20:00:00.000-03:00",
    venueName: "Theatro Municipal",
    address: "Praca Ramos de Azevedo",
    city: "Sao Paulo",
    price: 98,
    currency: "BRL",
    capacity: 140,
    availableTickets: 41,
    seatingMode: "seat-map",
    status: "published",
    externalSource: "ticketmaster",
    externalId: "tm_ballet-dawn",
  },
  {
    id: "evt-van-gogh-immersive",
    title: "Van Gogh: Experiencia Imersiva",
    description: "Projecoes em grande escala, trilha sonora e salas sensoriais.",
    about:
      "Van Gogh: Experiencia Imersiva transforma pinturas, cartas e referencias do artista em ambientes de grande escala. As salas combinam projecoes, som e percursos sensoriais para criar uma visita mais emocional do que uma exposicao tradicional. O evento funciona bem para familias, casais e pessoas que querem consumir arte de um jeito acessivel, fotografavel e envolvente.",
    imageUrl:
      "https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=1200&q=80",
    startsAt: "2026-11-11T20:00:00.000-03:00",
    venueName: "Utopia Gallery",
    address: "Rua Harmonia, 220",
    city: "Sao Paulo",
    price: 64,
    currency: "BRL",
    capacity: 160,
    availableTickets: 58,
    seatingMode: "general-admission",
    status: "published",
    externalSource: "manual",
  },
  {
    id: "evt-climbing-center",
    title: "Climbing & Bouldering Center",
    description: "Aula experimental e pista aberta para familias e iniciantes.",
    about:
      "Climbing & Bouldering Center e uma atividade para quem quer experimentar escalada em um ambiente controlado e acompanhado. A sessao inclui orientacao inicial, aquecimento e tempo livre nas paredes de bouldering. O formato favorece iniciantes, criancas acompanhadas e grupos que procuram uma experiencia ativa sem precisar comprar equipamento proprio.",
    imageUrl:
      "https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80",
    startsAt: "2026-11-13T09:00:00.000-03:00",
    venueName: "Center Munich North",
    address: "Rua Norte, 890",
    city: "Sao Paulo",
    price: 42,
    currency: "BRL",
    capacity: 90,
    availableTickets: 27,
    seatingMode: "general-admission",
    status: "published",
    externalSource: "ticketmaster",
    externalId: "tm_climbing-center",
  },
  {
    id: "evt-titanic-immersive",
    title: "Titanic: The Immersive Exhibition",
    description: "Exposicao imersiva com cenarios, artefatos e audio guia.",
    about:
      "Titanic: The Immersive Exhibition combina cenarios, relatos historicos, artefatos e audio guia para reconstruir momentos marcantes da viagem. A visita alterna informacao, ambientacao e recursos visuais para criar uma narrativa facil de acompanhar. E uma opcao interessante para quem gosta de historia, exposicoes tematicas e experiencias culturais com forte apelo visual.",
    imageUrl:
      "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=80",
    startsAt: "2026-11-14T14:00:00.000-03:00",
    venueName: "Pokeptoshallo",
    address: "Av. das Artes, 1440",
    city: "Sao Paulo",
    price: 52,
    currency: "BRL",
    capacity: 200,
    availableTickets: 76,
    seatingMode: "general-admission",
    status: "published",
    externalSource: "manual",
  },
];
